import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { defaultRules, type Run, type Rule, type Decision } from '../shared/types';
import './style.css';
import { diffWordsWithSpace } from 'diff';
async function api<T>(path: string, options?: RequestInit): Promise<T> {
  const response = await fetch(path, { ...options, headers: { 'Content-Type': 'application/json', ...options?.headers } });
  const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Request failed'); return data;
}
function App() {
  const [original, setOriginal] = useState(''), [instruction, setInstruction] = useState('');
  const [revised, setRevised] = useState(''), [manual, setManual] = useState(false);
  const [rules, setRules] = useState<Rule[]>(() => { try { return JSON.parse(localStorage.getItem('difflens-rules') || 'null') || defaultRules; } catch { return defaultRules; } });
  const [run, setRun] = useState<Run | null>(null), [history, setHistory] = useState<Run[]>([]), [selected, setSelected] = useState('');
  const [tab, setTab] = useState('changes'), [view, setView] = useState('diff'), [busy, setBusy] = useState(''), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [config, setConfig] = useState<{ configured: boolean; model?: string }>({ configured: false });
  const [candidate, setCandidate] = useState('');
  const [feedbackDraft, setFeedbackDraft] = useState('');
  useEffect(() => { setFeedbackDraft(run?.edits.find(e => e.id === selected)?.feedback || ''); }, [selected, run?.id]);
  useEffect(() => { Promise.all([api<Run[]>('/api/runs'), api<typeof config>('/api/config')]).then(([h, c]) => { setHistory(h); setConfig(c); }).catch(e => setError(e.message)); }, []);
  useEffect(() => { localStorage.setItem('difflens-rules', JSON.stringify(rules)); }, [rules]);
  async function generate() {
    setBusy(manual ? 'Auditing revision…' : 'Revising and auditing…'); setError(''); setNotice('');
    try { const r = await api<Run>('/api/runs', { method: 'POST', body: JSON.stringify({ original, instruction, rules, ...(manual ? { revised } : {}) }) }); setRun(r); setHistory(h => [r, ...h]); setSelected(r.edits[0]?.id || ''); setTab('changes'); setView('diff'); }
    catch (e) { setError((e as Error).message); } finally { setBusy(''); }
  }
  async function update(id: string, decision: Decision, feedback?: string) {
    if (!run) return;
    const edit = run.edits.find(e => e.id === id)!;
    setBusy('Saving review…'); setError('');
    try { const r = await api<Run>(`/api/runs/${run.id}`, { method: 'PATCH', body: JSON.stringify({ edits: [{ id, decision, feedback: feedback ?? edit.feedback }] }) }); setRun(r); setHistory(h => h.map(x => x.id === r.id ? r : x)); }
    catch (e) { setError((e as Error).message); } finally { setBusy(''); }
  }
  const edit = run?.edits.find(e => e.id === selected);
  const flagged = run?.edits.filter(e => e.flag).length || 0;
  const reviewed = run?.edits.filter(e => e.decision !== 'pending').length || 0;
  const finalText = run?.segments.map(s => s.text ?? (() => { const e = run.edits.find(e => e.id === s.editId)!; return e.decision === 'accepted' ? e.after : e.before; })()).join('') || '';
  function exportRun() { if (!run) return; const url = URL.createObjectURL(new Blob([JSON.stringify({ ...run, finalText }, null, 2)], { type: 'application/json' })); const a = document.createElement('a'); a.href = url; a.download = `difflens-${run.id}.json`; a.click(); URL.revokeObjectURL(url); }
  async function propose() { setBusy('Finding a recurring preference…'); setError(''); try { const result = await api<{rule: string | null}>('/api/rules/infer', {method: 'POST', body: '{}'}); setCandidate(result.rule || ''); if (!result.rule) setNotice('No recurring preference found in the feedback yet.'); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  return <div className="app">
    <aside className="rail"><a className="brand" href="/" aria-label="DiffLens home"><span className="logo">D<span>↗</span></span>DiffLens<span className="version">LAB</span></a><div className="rail-section">YOUR WORKSPACE</div><button className="nav active" onClick={() => { setRun(null); setSelected(''); }}>▧ <span>Revision workspace</span><span>↗</span></button><div className="rail-section sessions-title">RECENT REVISIONS <span>{history.length}</span></div><div className="sessions">{history.length === 0 ? <p className="muted">Your revisions will appear here.</p> : history.map((h) => <button key={h.id} className={`session ${run?.id === h.id ? 'current' : ''}`} onClick={() => {setRun(h); setSelected(h.edits[0]?.id || '');setTab('changes');}}><span className="session-icon">¶</span><span><strong>{h.original.slice(0,40)}…</strong><small>{new Date(h.createdAt).toLocaleDateString()} · {h.edits.length} edits</small></span></button>)}</div><div className="rail-bottom"><span className={`dot ${config.configured ? '' : 'off'}`}/><div><strong>{config.configured ? 'API connected' : 'API not configured'}</strong><small>{config.model || 'Check your server configuration'}</small></div></div></aside>
    <main><header className="topbar"><span>Workspace <span className="slash">/</span> Scientific revision</span><div className="top-actions"><select aria-label="Recent revisions" className="history-dropdown" value={run?.id || ""} onChange={e => {const h=history.find(x => x.id === e.target.value); if(h){setRun(h);setSelected(h.edits[0]?.id || "");setTab("changes");}}}><option value="">Recent revisions</option>{history.map(h => <option key={h.id} value={h.id}>{h.original.slice(0,30)}…</option>)}</select><span className="pill">RESEARCH PROTOTYPE</span></div></header><div className="content"><div className="page-heading"><div className="eyebrow">WRITE WITH INTENT. REVIEW WITH CONTEXT.</div><h1>Every change, accounted for.</h1><p>Revise your passage. See what changed—and whether it should have.</p></div>
    {error && <div role="alert" className="alert">{error}<button onClick={() => setError('')}>×</button></div>}{notice && <div role="status" className="notice">{notice}</div>}
    <div className="workspace"><div className="left-column"><section className="card source"><div className="card-heading"><h2><span className="step">01</span> Source passage</h2></div><textarea aria-label="Source passage" value={original} onChange={e => setOriginal(e.target.value)} placeholder="Paste a scientific passage…"/><div className="source-footer"><span>Plain text · passage-level review</span><span>{original.trim().split(/\s+/).filter(Boolean).length} words</span></div></section>
    <section className="card instructions"><div className="card-heading"><h2><span className="step">02</span> Editing instruction</h2><span className="tiny-label">ONE CLAUSE PER LINE</span></div><textarea aria-label="Editing instruction" value={instruction} onChange={e => setInstruction(e.target.value)} placeholder="What should change? What must stay?"/><div className="manual-toggle"><label><input type="checkbox" checked={manual} onChange={e => setManual(e.target.checked)}/> I already have a proposed revision</label></div>{manual && <textarea className="manual-input" aria-label="Proposed revision" value={revised} onChange={e => setRevised(e.target.value)} placeholder="Paste the proposed revision…"/>}<div className="generate-row"><span>Checked against {rules.filter(r => r.enabled).length} standing rules</span><button className="primary" onClick={generate} disabled={!!busy || !config.configured || !original.trim() || !instruction.trim() || (manual && !revised.trim())}>{busy || (manual ? 'Audit revision ↗' : 'Revise & audit ↗')}</button></div></section>
    <section className="card review"><div className="card-heading"><h2><span className="step">03</span> Review the revision</h2>{run && <span className="review-count">{reviewed} / {run.edits.length} reviewed</span>}</div><div className="tabs"><button className={tab === 'changes' ? 'selected' : ''} onClick={() => setTab('changes')}>Changes {run && <span>{run.edits.length}</span>}</button><button className={tab === 'instruction' ? 'selected' : ''} onClick={() => setTab('instruction')}>Instruction audit</button></div>
    {!run ? <div className="empty"><div className="empty-icon">≋</div><h3>A clearer view of your revision</h3><p>Your changes and fidelity audit will appear here.<br/>Start with a passage and an editing instruction.</p><div className="legend"><span><i className="green"/> Added</span><span><i className="red"/> Removed</span><span><i className="amber"/> Needs attention</span></div></div> : tab === 'instruction' ? <div className="clause-list">{run.clauses.map(c => <div className="clause" key={c.id}><div><span className="tiny-label">{c.kind}</span><span className={`status ${c.status}`}>{c.status === 'review' ? 'Needs review' : c.status}</span></div><h3>{c.text}</h3><div className="edit-links">{c.editIds.map(id => <button key={id} onClick={() => {setSelected(id);setTab('changes');}}>{id.toUpperCase()} ↗</button>)}{!c.editIds.length && <span className="muted">No linked edits</span>}</div></div>)}</div> : <><div className="review-toolbar"><span><i className="amber"/> {flagged} {flagged === 1 ? 'change needs' : 'changes need'} attention</span><div className="segmented"><button className={view === 'diff' ? 'on' : ''} onClick={() => setView('diff')}>Unified diff</button><button className={view === 'final' ? 'on' : ''} onClick={() => setView('final')}>Your result</button></div></div><div className="passage">{view === 'final' ? finalText : run.segments.map((s,i) => { if (s.text !== undefined) return <React.Fragment key={i}>{s.text}</React.Fragment>; const e = run.edits.find(e => e.id === s.editId)!; return <button key={i} title={e.reason} className={`inline-edit ${e.flag ? 'flagged' : ''} ${selected === e.id ? 'focused' : ''} ${e.decision}`} onClick={() => setSelected(e.id)} aria-label={`Review ${e.id}: ${e.before} to ${e.after}`}>{diffWordsWithSpace(e.before,e.after).map((p,k) => p.removed ? <del key={k}>{p.value}</del> : p.added ? <ins key={k}>{p.value}</ins> : <React.Fragment key={k}>{p.value}</React.Fragment>)}{e.flag && <sup>!</sup>}</button>; })}</div>{!run.edits.length && <p className="no-changes">No changes in this revision.</p>}<div className="review-footer"><span>{view === 'final' ? 'Accepted edits applied; pending and rejected edits retain the original.' : 'Select a highlighted change to inspect and review it.'}</span><button className="text-button" onClick={exportRun}>Export JSON ↓</button></div></>}
    </section></div>
    <aside className="right-column"><section className="card constitution"><div className="card-heading"><h2>Standing rules</h2><span className="rules-icon">☷</span></div><p className="card-description">Your constitution for scientific revision. Applied to every new revision.</p><div className="rule-list">{rules.map((r,i) => <div className="rule" key={r.id}><div className="rule-top"><span>RULE {String(i+1).padStart(2,'0')}</span><button className={`toggle ${r.enabled ? 'enabled' : ''}`} aria-label={`${r.enabled ? 'Disable' : 'Enable'} rule ${i+1}`} aria-pressed={r.enabled} onClick={() => setRules(rs => rs.map(x => x.id === r.id ? {...x,enabled:!x.enabled}:x))}><i/></button></div><textarea aria-label={`Rule ${i+1}`} value={r.text} onChange={e => setRules(rs => rs.map(x => x.id === r.id ? {...x,text:e.target.value}:x))}/><button className="remove-rule" onClick={() => setRules(rs => rs.filter(x => x.id !== r.id))}>Remove</button></div>)}</div><button className="add-rule" onClick={() => setRules(rs => [...rs,{id:crypto.randomUUID(),text:'',enabled:true}])}>+ Add a standing rule</button></section>
    {edit && tab === 'changes' && <section className="card edit-detail" key={`${run?.id}-${edit.id}`}><div className="card-heading"><h2>Change {edit.id.slice(1).padStart(2,'0')}</h2><span className={`badge ${edit.flag ? 'warning' : ''}`}>{edit.flag ? 'Needs attention' : 'No flag'}</span></div><div className="detail-body"><div className="before-after"><small>ORIGINAL</small><p>{edit.before || '(insertion)'}</p><small>PROPOSED</small><p>{edit.after || '(deletion)'}</p></div><div className="reason"><strong>{edit.flag ? 'Fidelity concern' : 'Audit assessment'}</strong><p>{edit.reason}</p></div><label className="feedback-label">Your reason or correction<textarea aria-label="Feedback on selected edit" value={feedbackDraft} onChange={e => setFeedbackDraft(e.target.value)} placeholder="What should the model preserve?"/></label><button className="text-button" disabled={!!busy || feedbackDraft === edit.feedback} onClick={() => update(edit.id, edit.decision, feedbackDraft)}>Save feedback</button><div className="decision-buttons"><button disabled={!!busy} className={edit.decision === 'accepted' ? 'chosen accept' : ''} onClick={() => update(edit.id,'accepted',feedbackDraft)}>✓ Accept</button><button disabled={!!busy} className={edit.decision === 'rejected' ? 'chosen reject' : ''} onClick={() => update(edit.id,'rejected',feedbackDraft)}>× Reject</button></div>{edit.decision !== 'pending' && <button className="text-button undo" disabled={!!busy} onClick={() => update(edit.id,'pending',feedbackDraft)}>Undo decision</button>}</div></section>}
    <section className="learning"><span className="spark">✧</span><h3>A constitution that learns</h3><p>Explain rejected changes. Recurring feedback can become a reusable rule.</p><button disabled={!!busy} onClick={propose}>Propose a rule ↗</button>{candidate && <div className="candidate"><textarea aria-label="Proposed standing rule" value={candidate} onChange={e => setCandidate(e.target.value)}/><div><button onClick={() => {setRules(rs => [...rs,{id:crypto.randomUUID(),text:candidate,enabled:true}]);setCandidate('');}}>Add rule</button><button onClick={() => setCandidate('')}>Dismiss</button></div></div>}</section></aside></div><footer className="page-footer"><span>DiffLens <span> / </span> Auditing the fidelity of scientific revisions</span><span>Model judgments support your review. You make the final call.</span></footer></div></main>
  </div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
